### ISSUE TITLE
Docker x Hacktoberfest 2022

### ISSUE THREAD

**Issue by ajeetraina** [FranckPachot/yugabytedb-docker-extension#1]
Just to let you know that Docker is participating in Hacktoberfest this year.
https://docker.com/hacktoberfest

In order to improve this extension and let community contribute to it, it would be great if you can get it added to our list of hacktoberfest at https://github.com/docker/hacktoberfest-2022

All you need to do is tag hacktoberfest to this repo and then raise [PR](https://github.com/docker/hacktoberfest-2022/pulls) to get contributions from the community members.

LMK what do you think?

**Comment by FranckPachot** [comment]
Done, thanks
